
import rclpy
import os
import gym
from gym.utils import seeding
from std_srvs.srv import Empty
from gazebo_connection import RobotArmEnvByFrank
#from .controllers_connection import ControllersConnection
#https://bitbucket.org/theconstructcore/theconstruct_msgs/src/master/msg/RLExperimentInfo.msg
#from openai_ros.msg import RLExperimentInfo
from biped_gym.utils import ut_param_server

# https://github.com/openai/gym/blob/master/gym/core.py
class RobotGazeboEnv(gym.Env):

    def __init__(self, reset_controls):
        # To reset Simulations
        rclpy.init()
        self.node=rclpy.create_node(self.__class__.__name__)
        robot_names = ut_param_server.getRobots(self.node)
        self.robot_name = robot_names[0]
        self._robot_resetter = self.node.create_client(Empty, '/'+self.robot_name+'/reset')
        self.gazebo = RobotArmEnvByFrank(self.node)
        #self.controllers_object = ControllersConnection(namespace=robot_name_space, controllers_list=controllers_list)
        self.reset_controls = reset_controls
        self.seed()

        # Set up ROS related variables
        self.episode_num = 0
        self.cumulated_episode_reward = 0
        #self.reward_pub = rospy.Publisher('/openai/reward', RLExperimentInfo, queue_size=1)

    # Env methods
    def seed(self, seed=None):
        self.np_random, seed = seeding.np_random(seed)
        return [seed]

    def step(self, action):
        """
        Function executed each time step.
        Here we get the action execute it in a time step and retrieve the
        observations generated by that action.
        :param action:
        :return: obs, reward, done, info
        """

        """
        Here we should convert the action num to movement action, execute the action in the
        simulation and get the observations result of performing that action.
        """
        
        self.gazebo.unpauseSim()
        self.executeAction(action)  #TODO add action need to use 1-? 2-?
        self.gazebo.pauseSim()
        obs = self._get_obs()
        done = self._is_done(obs)
        info = {}
        reward = self._compute_reward(obs, done)
        self.cumulated_episode_reward += reward


        return obs, reward, done, info

    def reset(self):
        self._reset_sim()
        self._init_env_variables()
        self._update_episode()
        obs = self._get_obs()
        return obs

    def close(self):
        """
        Function executed when closing the environment.
        Use it for closing GUIS and other systems that need closing.
        :return:
        """

    def _update_episode(self):
        """
        Publishes the cumulated reward of the episode and 
        increases the episode number by one.
        :return:
        
        self._publish_reward_topic(
                                    self.cumulated_episode_reward,
                                    self.episode_num
                                    )
        """
        self.episode_num += 1
        self.cumulated_episode_reward = 0
        

    '''def _publish_reward_topic(self, reward, episode_number=1):  #TODO use for publish purposes
        """
        This function publishes the given reward in the reward topic for
        easy access from ROS infrastructure.
        :param reward:
        :param episode_number:
        :return:
        """
        reward_msg = RLExperimentInfo()
        reward_msg.episode_number = episode_number
        reward_msg.episode_reward = reward
        self.reward_pub.publish(reward_msg)'''

    # Extension methods
    # ---------------------------- 
    def resetController(self):  
        """Sets the Robot in its init pose
        """
        raise NotImplementedError()

            
    def _reset_sim(self):
        """Resets a simulation
        """
        if self.reset_controls :
            self.gazebo.unpauseSim()
            #self.controllers_object.reset_controllers()
            #self._check_all_systems_ready()
            #self._set_init_pose()
            self.gazebo.pauseSim()
            #self.resetController()
            self.gazebo.resetSim()
            self.gazebo.unpauseSim()
            #self.controllers_object.reset_controllers()
            #self._check_all_systems_ready()
            self.gazebo.pauseSim()
            
        else:
            self.gazebo.unpauseSim()
            #self._check_all_systems_ready()
            #self._set_init_pose()
            self.gazebo.pauseSim()
            self.gazebo.resetSim()
            self.gazebo.unpauseSim()
            #self._check_all_systems_ready()
            self.gazebo.pauseSim()
            
        
        return True

    def _set_init_pose(self):
        """Sets the Robot in its init pose
        """
        raise NotImplementedError()

    def _check_all_systems_ready(self):
        """
        Checks that all the sensors, publishers and other simulation systems are
        operational.
        """
        raise NotImplementedError()

    def _get_obs(self):
        """Returns the observation.
        """
        raise NotImplementedError()

    def _init_env_variables(self):
        """Inits variables needed to be initialised each time we reset at the start
        of an episode.
        """
        raise NotImplementedError()

    def executeAction(self, action):
        """Applies the given action to the simulation.
        """
        raise NotImplementedError()

    def _is_done(self, observations):
        """Indicates whether or not the episode is done ( the robot has fallen for example).
        """
        raise NotImplementedError()

    def _compute_reward(self, observations, done):
        """Calculates the reward to give based on the observations given.
        """
        raise NotImplementedError()

    def _env_setup(self, initial_qpos):
        """Initial configuration of the environment. Can be used to configure initial state
        and extract information from the simulation.
        """
        raise NotImplementedError()

